### ISSUE TITLE
Variante couleur bleue

### ISSUE THREAD

**Issue by DuaelFr** [insoumis-local/wordpress-template-legislatives#10]
Dans les options de personnalisation, proposer une variante colorimétrique pour avoir les barres bleues plutôt que rouges.

Pour note : voilà ce qui peut être placé dans la zone de custom CSS pour y parvenir. À adapter avec une option qui ajoute une classe au body.

```css
.navbar-inverse, .navbar-secondary {
    background-color: #25B8CF;}

.navbar-inverse .navbar-nav>.active>a, .navbar-inverse .navbar-nav>.active>a:focus, .navbar-inverse .navbar-nav>.active>a:hover, .navbar-secondary .navbar-nav>.active>a, .navbar-secondary .navbar-nav>.active>a:focus, .navbar-secondary .navbar-nav>.active>a:hover {
    color: #fff;
    background-color: #027D8E;
}

.navbar-inverse .navbar-nav>.open>a, .navbar-inverse .navbar-nav>.open>a:focus, .navbar-inverse .navbar-nav>.open>a:hover, .navbar-secondary .navbar-nav>.open>a, .navbar-secondary .navbar-nav>.open>a:focus, .navbar-secondary .navbar-nav>.open>a:hover {
background-color: #027D8E;
}

.navbar-inverse .navbar-nav>li>a:focus,.navbar-inverse .navbar-nav>li>a:hover,.navbar-secondary .navbar-nav>li>a:focus,.navbar-secondary .navbar-nav>li>a:hover{
color:#fff;
background-color:#0098B6;
}

footer.content-info {
    border-top: 40px solid #25B8CF;
}
```
